# Generated by Django 5.2.1 on 2025-05-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
