# Generated by Django 5.2.2 on 2025-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
