# Generated by Django 5.2.1 on 2025-05-21 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.mahalla')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.village')),
            ],
        ),
        migrations.AddField(
            model_name='mahalla',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahallalar', to='news.village'),
        ),
        migrations.CreateModel(
            name='Healthcare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.mahalla')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.village')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.mahalla')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.village')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.mahalla')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.village')),
            ],
        ),
        migrations.CreateModel(
            name='WaterSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.mahalla')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.village')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mahalla',
            unique_together={('name', 'village')},
        ),
    ]
