# Generated by Django 5.2.1 on 2025-05-21 11:58

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news_videos/', validators=[news.models.validate_mp4]),
        ),
    ]
