# Generated by Django 5.2.1 on 2025-05-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mahalla',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='mahalla',
            name='villages',
            field=models.ManyToManyField(related_name='mahallalar', to='news.village'),
        ),
        migrations.RemoveField(
            model_name='mahalla',
            name='village',
        ),
    ]
