# Generated by Django 5.2.2 on 2025-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_mahalla_unique_together_mahalla_villages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='contentRu',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='titleRu',
        ),
        migrations.AddField(
            model_name='news',
            name='contentUz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='department',
            field=models.CharField(choices=[('electric', 'Elektr'), ('water', 'Suv'), ('education', "Ta'lim"), ('healthcare', 'Sog‘liqni saqlash'), ('police', 'Ichki ishlar'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='titleUz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
