# Generated by Django 5.2.2 on 2025-06-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_content_news_contentru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nameUz', models.CharField(max_length=100)),
                ('nameRu', models.CharField(max_length=100)),
                ('descriptionUz', models.TextField()),
                ('descriptionRu', models.TextField()),
                ('contact_phone', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('hours', models.CharField(max_length=100)),
                ('icon', models.CharField(default='other', max_length=50)),
                ('color', models.CharField(default='bg-gray-500', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='department',
            field=models.CharField(choices=[('electricity', 'Elektr'), ('gas', 'Gaz'), ('police', 'Politsiya'), ('internal-affairs', 'Ichki ishlar'), ('water', 'Suv'), ('education', "Ta'lim"), ('health', 'Sog‘liqni saqlash'), ('transport', 'Transport'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
    ]
