# Generated by Django 5.2.2 on 2025-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_department_alter_news_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='contact_email',
            new_name='contactEmail',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='contact_phone',
            new_name='workingHours',
        ),
        migrations.RemoveField(
            model_name='department',
            name='descriptionRu',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='department',
            name='nameRu',
        ),
        migrations.AddField(
            model_name='department',
            name='contactPhone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='nameUz',
            field=models.CharField(max_length=255),
        ),
    ]
