# Generated by Django 5.2.2 on 2025-06-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_contact_email_department_contactemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Village', models.ManyToManyField(to='news.village')),
                ('mahalla', models.ManyToManyField(to='news.mahalla')),
            ],
        ),
    ]
