# Generated by Django 5.2.2 on 2025-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_gas'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahallas', models.ManyToManyField(related_name='gas_supplies', to='news.mahalla')),
                ('villages', models.ManyToManyField(related_name='gas_supplies', to='news.village')),
            ],
        ),
        migrations.DeleteModel(
            name='Gas',
        ),
    ]
