# Generated by Django 5.2.3 on 2025-06-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_gassupply_delete_gas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='mahalla',
        ),
        migrations.RemoveField(
            model_name='education',
            name='village',
        ),
        migrations.RemoveField(
            model_name='electricsupply',
            name='mahalla',
        ),
        migrations.RemoveField(
            model_name='electricsupply',
            name='village',
        ),
        migrations.RemoveField(
            model_name='healthcare',
            name='mahalla',
        ),
        migrations.RemoveField(
            model_name='healthcare',
            name='village',
        ),
        migrations.RemoveField(
            model_name='policenotice',
            name='mahalla',
        ),
        migrations.RemoveField(
            model_name='policenotice',
            name='village',
        ),
        migrations.RemoveField(
            model_name='watersupply',
            name='mahalla',
        ),
        migrations.RemoveField(
            model_name='watersupply',
            name='village',
        ),
        migrations.AddField(
            model_name='education',
            name='mahalla',
            field=models.ManyToManyField(related_name='education_mahalla', to='news.mahalla'),
        ),
        migrations.AddField(
            model_name='education',
            name='village',
            field=models.ManyToManyField(related_name='education_village', to='news.village'),
        ),
        migrations.AddField(
            model_name='electricsupply',
            name='mahalla',
            field=models.ManyToManyField(related_name='electricsupply_mahalla', to='news.mahalla'),
        ),
        migrations.AddField(
            model_name='electricsupply',
            name='village',
            field=models.ManyToManyField(related_name='electricsupply_village', to='news.village'),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='mahalla',
            field=models.ManyToManyField(to='news.mahalla'),
        ),
        migrations.AddField(
            model_name='healthcare',
            name='village',
            field=models.ManyToManyField(to='news.village'),
        ),
        migrations.AddField(
            model_name='policenotice',
            name='mahalla',
            field=models.ManyToManyField(to='news.mahalla'),
        ),
        migrations.AddField(
            model_name='policenotice',
            name='village',
            field=models.ManyToManyField(to='news.village'),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='mahalla',
            field=models.ManyToManyField(related_name='watersupply_mahalla', to='news.mahalla'),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='village',
            field=models.ManyToManyField(related_name='watersupply_village', to='news.village'),
        ),
    ]
