# Generated by Django 5.2.3 on 2025-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_education_mahalla_remove_education_village_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gassupply',
            name='mahallas',
        ),
        migrations.RemoveField(
            model_name='gassupply',
            name='villages',
        ),
        migrations.AddField(
            model_name='gassupply',
            name='mahalla',
            field=models.ManyToManyField(related_name='gassupply_mahalla', to='news.mahalla'),
        ),
        migrations.AddField(
            model_name='gassupply',
            name='village',
            field=models.ManyToManyField(related_name='gassupply_village', to='news.village'),
        ),
    ]
