# Generated by Django 5.2.3 on 2025-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_gassupply_mahallas_remove_gassupply_villages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policenotice',
            name='mahalla',
            field=models.ManyToManyField(related_name='policenotice_mahalla', to='news.mahalla'),
        ),
        migrations.AlterField(
            model_name='policenotice',
            name='village',
            field=models.ManyToManyField(related_name='policenotice_village', to='news.village'),
        ),
    ]
